services:
  - type: web
    name: fullstack-app
    env: node
    rootDir: .
    buildCommand: |
      npm install --prefix backend
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: node backend/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
