services:
  - type: web
    name: fullstack-app
    env: node
    rootDir: backend
    buildCommand: |
      npm install --prefix ../frontend
      npm run build --prefix ../frontend
      npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
