services:
  - type: web
    name: fullstack-app
    env: node
    rootDir: .
    buildCommand: |
      cd backend && npm install
      cd ../frontend && npm install && npm run build
    startCommand: node backend/src/index.js
    envVars:
      - key: NODE_ENV
        value: production
